# word2vec calculation using vanilla numpy

In [2]:
import numpy as np
import math

In [3]:
def sigmoid(z):
    if z > 6:
        return 1.0
    elif z < -6:
        return 0.0
    else:
        return 1 / (1 + math.exp(-z))

In [4]:
vocab = 3

In [18]:
for dim in [10]:
    nn0 = np.random.uniform(low=-0.5/dim, high=0.5/dim, size=(vocab, dim))
    nn1 = np.zeros(shape=(vocab, dim))


In [19]:
nn0

array([[ 0.0161753 , -0.04843434, -0.01414273, -0.03934054, -0.00532933,
         0.0389679 ,  0.01720741,  0.04131523,  0.04075988, -0.01870027],
       [-0.01933933,  0.00607345, -0.02728657,  0.00350739,  0.0152188 ,
         0.03878666,  0.01454909,  0.01862472,  0.01902664, -0.02755737],
       [ 0.03835532, -0.04315784, -0.02480194,  0.00943505,  0.0015113 ,
        -0.01373617,  0.03045477, -0.04658463, -0.04075474, -0.02727382]])

In [7]:
nn1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
nn0[1]

array([-0.02481709, -0.02641891, -0.00042852, -0.03077878, -0.00757023,
       -0.00070581, -0.02058206,  0.00203994, -0.04003963, -0.03123642])

In [16]:
np.dot([4,3,2],[9,2,3])

48

In [34]:
z = np.dot(nn0[1], nn1[1])

In [35]:
z

0.0

In [39]:
p = sigmoid(z)

In [40]:
p

0.5

In [42]:
alpha = 0.01
label = 0

In [43]:
g = alpha * (label - p)

In [55]:
g

-0.005

In [46]:
neu1e = np.zeros(10)
neu1e

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
neu1e += g * nn1[1] 
neu1e

array([ 2.75287809e-06,  3.28666750e-06,  3.61396031e-06, -3.24100445e-06,
       -2.92111690e-06,  3.43909600e-06, -2.72029663e-06,  3.09316815e-07,
        6.97578708e-07, -1.14771069e-06])

In [51]:
nn1[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
nn1[1] += g * nn0[1]

In [53]:
nn1

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.83525206e-04, -2.19111167e-04, -2.40930687e-04,
         2.16066963e-04,  1.94741127e-04, -2.29273067e-04,
         1.81353109e-04, -2.06211210e-05, -4.65052472e-05,
         7.65140461e-05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00]])

In [58]:
nn0[1] * -0.005

array([-1.83525206e-04, -2.19111167e-04, -2.40930687e-04,  2.16066963e-04,
        1.94741127e-04, -2.29273067e-04,  1.81353109e-04, -2.06211210e-05,
       -4.65052472e-05,  7.65140461e-05])

In [62]:
nn0[1] += neu1e

In [63]:
nn0

array([[-0.04152885, -0.0261688 , -0.03221715, -0.02237916, -0.02589876,
        -0.03596906,  0.00058227,  0.00089504, -0.04046292, -0.03041827],
       [ 0.03670779,  0.04382552,  0.04818975, -0.04321663, -0.03895115,
         0.04585805, -0.03627334,  0.00412453,  0.00930175, -0.01530396],
       [ 0.04308569, -0.01316674, -0.04224658,  0.04199693,  0.00744445,
        -0.0224658 ,  0.03658869,  0.03602895, -0.04176357,  0.01980431]])